### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by whwh747** [lif314/GS3LAM#3]
Thank you for your excellent work. I would like to ask if depth_sil and alpha are the same thing? I noticed that your depth and RGB are rendered together. Is this depth different from the depth rendered separately in splatam?

**Comment by lif314** [comment]
In fact, they are the same. Using cumulative opacity masks to expand 3D Gaussians was first used in GS-SLAM [1]. This is called silhouette in Splatam, but they are essentially the same. They are the result of alpha blending after opacity splating of Gaussians to the pixel plane. In addition, the depth of both uses alpha blending, which is the same. 

[1] GS-SLAM: Dense Visual SLAM with 3D Gaussian Splatting, CVPR 2024.

**Comment by whwh747** [comment]
I got it, thank you very much!
