### ISSUE TITLE
environment issue

### ISSUE THREAD

**Issue by whwh747** [lif314/GS3LAM#4]
i follow pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117 and meet a error ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dash 2.16.1 requires importlib-metadata, which is not installed.
open3d 0.17.0 requires pyyaml>=5.4.1, which is not installed.
wandb 0.17.0 requires pyyaml, which is not installed.
pypose 0.6.8 requires torch==2.*, but you have torch 1.13.1+cu117 which is incompatible.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 1.13.1+cu117 which is incompatible.

**Comment by whwh747** [comment]
![微信截图_20241202111629](https://github.com/user-attachments/assets/6a09a927-ddd1-46dd-9d5b-480c60df4a79)

**Comment by lif314** [comment]
> Yes, I followed the installation instructions, but my CUDA version is 11.8.


Oh, you should install the version of torch and cuda-toolkit that corresponds to the CUDA version you are using.

**Comment by whwh747** [comment]
thank you, i will try it again!
