### ISSUE TITLE
The problem of selecting the output dimension of the decoder

### ISSUE THREAD

**Issue by SkyAndFly** [lif314/GS3LAM#7]
非常感谢作者开源的代码！我在阅读你们论文和源码后有一些疑问，希望可以得到解答。

1. 在代码中semantic decoder的输出维度配置是256。我理解的论文中说的意思，这个输出维度是语义标签类别数量，但我注意到scannet标签的类别数量不是256个。请问为何选择输出维度256呢？
2. 加载scannet数据集的label图片是转成了uint8。请问这是使用了scannet预处理转成nyu40 label的图片吗?未做预处理之前，label图应该是16bits的png。

**Comment by lif314** [comment]
@SkyAndFly 感谢你对这个项目感兴趣，一下是对你的回复：

1. 我们最初的设计是采用DEVA生成伪语义标签作为真值，但发现这些SAM model在长序列数据上无法保证帧间一致性，所以“被迫”采用了数据集提供的语义标签。256只是一个“大”的语义类别数量，对于采用DEVA获得的伪语义标签，在增量重建过程中，我们很难确定具体有多少类别，所以它是一个“估计”的语义类别数量，尽可能包含场景中所有的语义类别即可。当然，你可以根据你的场景随意改变这个值，并没有太大的影响。如果你的场景类别较多，你可能还需要修改高斯语义特征的维度，比如从16改到64等等。

2. 我们没有对scannet进行预处理。由于256是我们设置的最大语义标签类别数量，所以我们转成了uint8。当然，一些大于254的类别可能被转换到0-254之间，好在，scannet的语义标签并不多。同1，如果你的场景语义类别特别多，你可以改变语义类别数量或进行简单的预处理，合并一些语义标签。
